version: "3.8"

services:
  postgres_db:
    image: postgres:latest
    container_name: tech-market-postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    restart: unless-stopped

  mongo_db:
    image: mongo:latest
    container_name: tech-market-mongo
    ports:
      - "27017:27017"
    restart: unless-stopped

  cassandra_db:
    image: cassandra:latest
    container_name: tech-market-cassandra
    ports:
      - "9042:9042"
    restart: unless-stopped
